### ISSUE TITLE
find wrong chessboard with this image

### ISSUE THREAD

**Issue by fanzy1234** [onlyliucat/Multi-chessboard-Corner-extraction-detection-#2]
![box1-148](https://user-images.githubusercontent.com/29767973/85943069-7b5c7d00-b8e2-11ea-992e-2456f7404da4.png)
<img width="875" alt="屏幕快照 2020-06-28 上午1 56 55" src="https://user-images.githubusercontent.com/29767973/85943117-bc549180-b8e2-11ea-9780-eee87badfcfc.png">

**Comment by ZYYYY123324** [comment]
你好，请问一下Linux和Windows下运行有什么区别呢？
